# filepath: /C:/XM_Cloud_Certification_LearnerAI/config/tasks.yaml

get_and_show_XMCloud_content_task:
  description: >
    For the provided list of topics: {topicList},
    gather all relevant XM Cloud information and present it as a comprehensive 
    study resource. Include examples, exam tips, common questions, and sources.

  expected_output: >
    {{
      "topics": [...],
      "content": {{
        "<topic>": {{
          "explanation": "...",
          "example": "...",
          "exam_tips": "...",
          "common_questions": [...]
        }}
      }},
      "sources": {{
        "<topic>": "...source links..."
      }}
    }}



generate_quiz_task:
  description: >
    Generate a 10-question MCQ quiz for {topicList}.
    Each question must have multiple choices and exactly one correct answer.
  expected_output: >
    {
      "topics": [...],
      "questions": [
        {
          "question": "...",
          "options": [...],
          "correct_answer": "..."
        }
      ]
    }

retry_reaccess_task:
  description: >
    Reassess the user's quiz. Input includes the entire quiz plus userAnswers. 
    Output a revised quiz with clarifications or hints for incorrect answers.
  expected_output: >
    {
      "topics": [...],
      "questions": [
        {
          "question": "...",
          "options": [...],
          "correct_answer": "...",
          "hint": "..."
        }
      ]
    }
